# Generated by Django 4.1.3 on 2023-02-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
